# Generated by Django 3.0.2 on 2020-02-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_id', models.CharField(max_length=5, unique=True)),
                ('address', models.TextField()),
                ('atm_balance', models.BigIntegerField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Deactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=8, unique=True)),
                ('bank_name', models.TextField()),
                ('bank_headquarters', models.TextField()),
                ('bank_phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=5, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address', models.TextField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.Bank', to_field='bank_id')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(max_length=5, unique=True)),
                ('province_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=3, unique=True)),
                ('history_time', models.DateTimeField()),
                ('money', models.BigIntegerField()),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.ATM', to_field='atm_id')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=5, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=32)),
                ('emp_password', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.Branch', to_field='branch_id')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.Province', to_field='province_id'),
        ),
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(through='Long.Branch', to='Long.Province'),
        ),
        migrations.AddField(
            model_name='atm',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Long.Employee', to_field='employee_id'),
        ),
    ]
