# Generated by Django 3.0.2 on 2020-03-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(verbose_name='d/m/Y'),
        ),
    ]
