# Generated by Django 3.0.2 on 2020-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0003_transaction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
