# Generated by Django 3.0.2 on 2020-02-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0005_transaction_receive_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
