# Generated by Django 3.0.2 on 2020-02-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Long', '0002_auto_20200211_1556'),
        ('Hoang', '0005_transaction_receive_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(default='CTG01', on_delete=django.db.models.deletion.CASCADE, to='Long.Branch', to_field='branch_id'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
