# Generated by Django 3.0.2 on 2020-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0006_transaction_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
